### PR TITLE
Content encoding fix

### PR DESCRIPTION
**Pull request by dparis**
There was a straightforward bug in the way the reader/base class handles the raw HTML content. The existing unicode conversion code was being called after the initial call to Pismo::Document.clean_html, which was causing the gsub! calls in clean_html to choke on some bad html. I just moved the call order around a little and wrote some additional logic to handle another corner case that cropped up.

I also pulled in the pull requests made by @bborn and @ashleyw, but my fixes don't depend on those so you should be able to isolate my commits if you want to just pull those in.

### CODE REVIEW

**Comment by peterc** [comment]
Wow! There's a bit much in this pull request in one go for me to analyze and merge quickly.. so I'll need to take some spare time and dig into it a bit. Thanks though, but it might take a couple of weeks for me to dig into this. In the interim, I will keep this request open.

**Comment by dparis** [comment]
No rush, I'll keep my fork active in the mean time. And like I mentioned, my last two bugfix commits (0bcb1e7 and 64cf7cf) aren't dependent on the changes from @bborn and @ashleyw, so if you want to just grab those for the encoding fix there shouldn't be any issues.

Let me know if you have any questions or need me to rework anything.

**Comment by peterc** [comment]
I've been getting a few nudges to do some serious work on Pismo over the last few months actually and a few offers to help with the refactoring I want to do (it needs to be more modular so you can pick and mix functionality, rather than a giant black box - @ashleyw's work started down that road).

It seems like this bundle of improvements and fixes will get it to a state where starting that refactoring will make more sense. However, I want the freedom to "break" things a little so may end up moving it up a major version number.

Once I start figuring this out, I'll try and invite everyone who's interested and/or has committed so far into some sort of discussion about the future design and implementation of Pismo since all input would be useful :-) Expect this soon.

**Comment by dparis** [comment]
Cool, good luck moving forward. I am just now starting on a project using Pismo as a jumping off point to scrape data which will be fed into a document classification algorithm. FWIW, it's still in the prototype phase, so I haven't built in any heavy dependencies on Pismo's API; as far as I'm concerned feel free to mix it up however you need!

Depending on how Pismo's modularity and extensibility develop, we may end up rolling our own custom scraper past the prototype phase, but for now it sure is a handy leg up on the dev process. I'll keep watching the repo, and thanks for your work.

**Comment by shyamster** [comment]
Stumbled upon Pismo and started using it for a project including changes from @dparis.  There still seems to be some more encoding bugs.  For example, this page causes "invalid byte sequence" error - http://diyblogger.net/what-have-i-learned-after-using-triberr-for-two-months-the-answer-may-surprise-you

**Comment by dparis** [comment]
@shyamster Entirely possible. My fix was mostly just a hotfix to solve an immediate problem I was encountering, and I unfortunately didn't have time to become familiar enough with the Pismo codebase to hunt down other corner cases. If I get some time, I can try to take a look at this and see if the fix is obvious; I suspect there are other places in Pismo that handle encoded content outside of the Reader class, or else other paths into the same Reader methods that bypass the content encoding checks.

I wouldn't plan any deadlines around further fixes from me, though, as we've moved on from Pismo to rolling our own internal content scraping system because we just needed a more robust way to get at the content of many different types of sites. The exact scheme will likely be proprietary, but it's based on a machine learning approach where the ML classifier is taught to distinguish between meaningful HTML content (text content, meta tags, etc) and useless content (tags and markup, javascript, etc). I am hoping, however, to take the underlying library I've built to power it and release that as a generic machine learning / document classification gem.

Not a knock on Pismo at all, it's quite handy! In fact, @peterc, since you mentioned discussing the future of the gem at some point, I might be able to suggest some machine learning approaches as a potential re-factor option for making the reader algorithms more flexible. Depends entirely on the terms of my disclosure agreement with my current client, but if I'm able to I'd be happy to chime in.

**Comment by RaVbaker** [comment]
@peterc When you will incorporate this pull into master and gem?

**Comment by aodioicq** [comment]
when can this be in gem? Having so many encoding errors

**Pull request merged**
