### PR TITLE
Merged cheald's refactors and made tests pass

### PR DESCRIPTION
**Pull request by bborn**
Include support for scraping images with relative paths and video embeds, as well as a better image scraping algorithm.

### CODE REVIEW

**Comment by bborn** [comment]
Updated to improve title extraction algothrithm

**Comment by peterc** [comment]
I haven't had time to go through this BUT from my overall understanding, you've basically taken most of the other requests and bundled them into one more easily digested package? If so, that makes my life a bit easier.

The reason I haven't merged the other pull request is it had a conflict with another and was complicated enough that I haven't found the time to spend on it. If I can instead do my testing and go through this single pull request instead to clear things up, I should be able to "make" the time ;-)

**Comment by bborn** [comment]
Yeah, I looked through all the network branches for the changes I thought were most relevant/important. Cheald's branch was the furthest along, so merged his into mine, and then merged your stuff back in and made tests pass.

**Comment by rastasheep** [comment]
@bborn can add support for https links too?

You just need to pass `:ssl_verify_mode => OpenSSL::SSL::VERIFY_NONE` as an option
to the open method.
Here: https://github.com/bborn/pismo/blob/master/lib/pismo/document.rb#L38

Tnx i would appreciated it :)

**Comment by peterc** [comment]
I wouldn't support such an addition (the suggested workaround for https links) for the reasons covered in this post: http://jamesgolick.com/2011/2/15/verify-none..html

However, the library is designed in such a way that you can certainly pass your own IO in or your own already-read-by-whatever-means-you-like HTML so you have the freedom to do that request yourself prior to the call to Pismo.

**Comment by rastasheep** [comment]
Oh, i didn't spotted that vulnerability, tnx for pointing that and quick response.

Do you have any tip for pulling info from https links in app for sharing links (i have link preview, like facebook statuses)? Is safe to pull it or not? Is result worth "risking"?

Thanks again

**Comment by peterc** [comment]
Unfortunately, I don't know. Security is one of my biggest blind spots :-) (which is why I'm trusting James on it) Personally, I'm not super concerned about man in the middle attacks if I'm just slurping data off the Web. If I were sending credit card numbers or similar data, that's a different story. So if you're just scraping stuff, take it down any way you can IMHO..

**Comment by archseer** [comment]
This needs to be merged, it has the features of #4, #14 as well as some additions.

**Pull request merged**
