### PR TITLE
fixes for extracting content from fastcompany pages

### PR DESCRIPTION
**Pull request by huned**
Love this gem. This PR includes fixes for extracting content from articles on fastcompany.
- included [this article](http://www.fastcompany.com/most-innovative-companies/2012/airbnb) in the corpus and updated `metadata_expected.yaml` in kind
- add `.node-byline` to `AUTHOR_MATCHES`
- reject empty string titles (not just nil titles)
- update a couple `LEDE_MATCHES` selectors to avoid fastcompany's `p.advertisement` elements
- tidying: append `pwd` to `$LOAD_PATH` so `rake console` works

### CODE REVIEW

**Comment by huned** [comment]
@peterc, any interest in merging this into master?

**Comment by huned** [comment]
@peterc ???

**Comment by peterc** [comment]
Sorry, I'm not going to be able to get back to this quickly. I've been in the US organizing a conference, writing a book, endless newsletters to keep publishing, a 4 month old in the house, a conference speech to write for next week.. My spare time is currently a fat zero so I have to catch up on GitHub when I can squeeze out the time.

I've not looked at this code yet but I'm not sure site specific rules are a way to go, but I could be wrong and I still need to look at it (but, all the above). As such, I'm not closing this and will wait until I have some time to check it out.

**Comment by peterc** [comment]
On a quick re-read of this, maybe it will be OK since it's not entirely site specific and the rules may also help other sites. (This is what I mean by lack of time. I have to read stuff in like 30 seconds ;-))

**Comment by huned** [comment]
thanks @peterc -- I understand your busy schedule. This is a useful library, so would love to keep sending PRs. Going forward I'll use my own fork but will also send PRs your way.

**Pull request merged**
